services:
  - type: web
    name: mehul-orders
    runtime: python
    plan: free
    buildCommand: "pip install -r server/requirements.txt"
    startCommand: "python3 server/app.py"
    envVars:
      - key: FIREBASE_ADMINSDK_JSON
        sync: false
